### ISSUE TITLE
Feature Request: Move mods in Batch Queue by X number of spaces instead of one at a time.

### ISSUE THREAD

**Issue by munchyfly** [ME3Tweaks/MassEffectModManager#361]
Frosty Mod Manager has a feature where, if you press Shift + The list arrows, it moves mods up/down by 5 spaces. I was wondering if it would be possible to implement this in Batch Queue as well.

You'd have the regular "one line at a time" and then, for example, if you press Shift + Move Up, it would move the mod up on the list by X number of spaces.

I've attached a video to show what I mean.

https://github.com/ME3Tweaks/ME3TweaksModManager/assets/28280399/d45517be-cc1f-4570-9a5b-d3883bc5996c

**Comment by Mgamerz** [comment]
This is implemented now in the the May 10 build of 8.1.
