### ISSUE TITLE
App crash (.net unhandled exception) 

### ISSUE THREAD

**Issue by stevecs** [ME3Tweaks/MassEffectModManager#364]
OS: windows server 2022 (21h2) w/ .NET 4.8 & .NET 3.5 installed
ME3Tweaks version: 8.1 Build 128

ME LE runs fine on system.  

Happens as soon as I click on 'start using mod manager' 

I am just testing out items on an older game system so wanted to file this in case it helps in fixing the code.

Event Logs below:

[AppError.txt](https://github.com/ME3Tweaks/ME3TweaksModManager/files/11453019/AppError.txt)
[NetRuntimeError.txt](https://github.com/ME3Tweaks/ME3TweaksModManager/files/11453020/NetRuntimeError.txt)

**Comment by Mgamerz** [comment]
This issue has been fixed in today's update. It was due to unexpected changes to my web server which served invalid data to the client.
