### ISSUE TITLE
Indefinite "Refreshing ME3Tweaks services"

### ISSUE THREAD

**Issue by BreakPoints** [ME3Tweaks/MassEffectModManager#365]
Since updating from 8.1 to a new 8.1 build today, ME3Tweaks gets stuck refreshing services thus locking out a good chunk of functionality. The older 8.1 build (from either yesterday or the day before) did not have this issue for me.

![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/11966090/89aeada0-95d5-4923-95fc-54bf5c24a8f6)

**Comment by Mgamerz** [comment]
This is not due to the build change, this is due to my web host changing some things and breaking them. It just coincided with the update time. It should be fixed server side.
