### ISSUE TITLE
Feature request: LE1 Bio2DA Merge

### ISSUE THREAD

**Issue by fightinfears** [ME3Tweaks/MassEffectModManager#373]
I was trying to make a mod that changed some of the values in the 2da table. But didn't know it couldn't be merged. Can only replace the whole table. So yeah it would be great if we had a 2da merge feature.

**Comment by Mgamerz** [comment]
There has been some work on this recently. No timeframe of when this will be released but there's time being dedicated to it now.

**Comment by Mgamerz** [comment]
Progress update - this should be implemented in current codebase and private alpha

**Comment by Mgamerz** [comment]
Implemented in 9.0
