### ISSUE TITLE
Cannot backup vanilla DVD ME2 install, says Engine.pcc is modified

### ISSUE THREAD

**Issue by mladenperisic** [ME3Tweaks/MassEffectModManager#378]
I installed ME2 from retail DVDs. Then I installed all DLCs from EA website and 1.03 patch from https://community.pcgamingwiki.com/files/file/1438-mass-effect-2-patch-103/

The game runs just fine.

When I try to do backup via Mod Manager I'm getting the error about file not being vanilla:
BioGame\CookedPC\Engine.pcc

This is from log:

> 2023-07-14 13:22:46.917 +02:00 [INF] [ME3TWEAKSCORE] PerformBackup() on C:\Program Files (x86)\Mass Effect 2
> 2023-07-14 13:22:46.922 +02:00 [INF] [ME3TWEAKSCORE] PerformBackup: Game is not running
> 2023-07-14 13:22:48.099 +02:00 [INF] [ME3TWEAKSCORE] Starting the backup thread. Checking path: C:\Program Files (x86)\Mass Effect 2
> 2023-07-14 13:22:48.100 +02:00 [INF] [ME3TWEAKSCORE] Checking target is vanilla
> 2023-07-14 13:22:48.103 +02:00 [INF] [ME3TWEAKSCORE] Extracting embedded file: ME3TweaksCore.Assets.VanillaDatabase.me2.bin to memory
> 2023-07-14 13:22:48.542 +02:00 [ERR] [ME3TWEAKSCORE] Non-vanilla file found: C:\Program Files (x86)\Mass Effect 2\BioGame\CookedPC\Engine.pcc
> 2023-07-14 13:22:49.133 +02:00 [INF] [ME3TWEAKSCORE] Checking DLC consistency
> 2023-07-14 13:22:49.134 +02:00 [INF] [ME3TWEAKSCORE] Checking only vanilla DLC is installed
> 2023-07-14 13:22:49.137 +02:00 [INF] [ME3TWEAKSCORE] Checking for TexturesMEM TFCs
> 2023-07-14 13:22:49.145 +02:00 [INF] [ME3TWEAKSCORE] Cannot backup: Game is modified

When I check SHA-256 and MD5 of Engine.pcc on both DVD (file data\other.rar\BioGame\CookedPC) and on HDD I'm getting the same results:

> SHA-256: 7c887ae4e819f08292fbe49adb68a4cf5e8b425ec3990dc2ddccfcd61fbeca35
> MD5: d70a7b02725b2f812e3df6faee5f97b1

Either my DVD is damaged or ME3TweaksCore.Assets.VanillaDatabase.me2.bin does not have valid signature.

ME3Tweaks Mod Manager is version 8.2.129

**Comment by mladenperisic** [comment]
On Discord I was asked to post Engine.pcc, so I'm posting it here.
[Engine.zip](https://github.com/ME3Tweaks/ME3TweaksModManager/files/12053008/Engine.zip)

Also, someone asked what is the version of my DVD. Mine is 1st from the list: https://www.mobygames.com/game/44900/mass-effect-2/releases/windows/
the one with UPC 014633159813 (that's also written on the back cover of DVD case).

**Comment by Mgamerz** [comment]
This should be fixed in the current beta build release.
