### ISSUE TITLE
Remember the last selected game (installation target)

### ISSUE THREAD

**Issue by VioletGiraffe** [ME3Tweaks/MassEffectModManager#389]
Just a small QOL deficiency, would be nice if the selected game was persisted across launches of the ME3TMM. Especially since the active tab in the mod library is already remembered, and I get a short startle every time I see that "Cannot install to this game" message.

**Comment by Mgamerz** [comment]
The last selected target will be persisted if the current target is considered active, which means it was able to be automatically looked up. If it is not finding it, your game is probably not properly installed, as Mod Manager uses a pretty-standard lookup from steam and EA app to find the games.
