### ISSUE TITLE
Remember the selected custom launch option

### ISSUE THREAD

**Issue by VioletGiraffe** [ME3Tweaks/MassEffectModManager#390]
The custom launch options is a nice feature. I remember you said it's a new function, so completely understandable it's not persisted across restarts, but it would be awesome if it was remembered! Especially in conjunction with #389.

**Comment by Mgamerz** [comment]
The custom launch configuration you last used should automatically be applied when you restart mod manager. It tracks the Guid of the config and applies it when you switch targets. It requires your mod library being available.
