### ISSUE TITLE
Switching between OT and LE requires restart for the mod library to display items

### ISSUE THREAD

**Issue by VioletGiraffe** [ME3Tweaks/MassEffectModManager#392]
After I switch between OT and LE (in any direction), my library is empty until I restart the ModManager. If it's unavoidable, a message prompting for restart would be nice. At first I was completely baffled, and very upset that my carefully crafted mod selection is gone.

**Comment by Mgamerz** [comment]
This could be improved, but it's not a high priority - this is a pretty rare occurrence. The mod library can be manually reloaded. Disabled generations don't load data to improve performance.

**Comment by VioletGiraffe** [comment]
Makes sense to not load when disabled, only slightly confusing that it doesn't load upon activation. But yes, no big deal, and a simple pop-up message could clear the confusion.

**Comment by Mgamerz** [comment]
Implemented in 9.0
