### ISSUE TITLE
Feature Request: Installation information - DLC mods Enable/Disable All Button

### ISSUE THREAD

**Issue by UtilityPawn** [ME3Tweaks/MassEffectModManager#398]
Is it possible that the installation information section could have a "enableall/disableall" mods button feature so we dont have to manually disable them one by one for mod testing/conflicts?

![Capture](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/154812945/d8cc2ed6-ed00-443a-af81-0b0948f8ea33)

**Comment by Mgamerz** [comment]
Implemented in 9.0
