### ISSUE TITLE
Feature Request: Batch Mod Installer to add more than one texture mod

### ISSUE THREAD

**Issue by UtilityPawn** [ME3Tweaks/MassEffectModManager#400]
can there be an option for batch mod installer to select mutiple mems? it can only select one texture at a time unlike mass effect modder where you can add all of them at once.
![Capture](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/154812945/14452fc0-b348-4db6-a211-240ae1203a8a)

**Comment by Mgamerz** [comment]
Implemented in 9.0
