### ISSUE TITLE
Feature Request: Add remove file from Multilist and remove Multilist in moddesc editor

### ISSUE THREAD

**Issue by munchyfly** [ME3Tweaks/MassEffectModManager#401]
Add remove file from MultiList and remove Multilist in moddesc editor

Kind of a nitpick but if I want to remove a file from a Multilist or remove a Multilist entirely, I have to edit the moddesc.ini itself. If at all possible, could a remove file from the list and remove a MultiList entirely button be added?

Terrible UI layout but I hope this shows what I mean:

![ME3TweaksModManager_GZaUbGRoYF](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/28280399/8e323cee-9c52-4909-94f7-df1bf0a6510b)

**Comment by Mgamerz** [comment]
![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/bbd07cac-7468-4d34-9105-dc6dd4bf5602)

This has been implemented and will be available in Mod Manager 9.

**Comment by Mgamerz** [comment]
Implemented in 9.0
