### ISSUE TITLE
Feature Request: Indicate which mods in the list are available for check for update

### ISSUE THREAD

**Issue by bladekey88** [ME3Tweaks/MassEffectModManager#403]
Would it be possible to add some sort of indication into the UI (maybe on the Mod Library list) as to which mods are checked as part of the update check vs those that don't. It would then make it easier for the end user to know which need to be manually checked on nexus (and also since mods not hosted on nexus aren't covered by the update anyway a double bonus I guess?)

**Comment by Mgamerz** [comment]
I know this is months later - I took a modding break. Do you have any ideas or concepts for how this would fit into the current UI? Maybe an option to show an icon (so it is not always visible in the list?)

**Comment by bladekey88** [comment]
an icon with that can be toggled, for either can update or can't update (but not both since that would be information overload I think). For the icon maybe the two arrows in a circle(for pro), or the same but with a cross through it (for can't)

I did think about colours but I think that might be too confusing and visually distracting.

**Comment by Mgamerz** [comment]
When an update check is occurring, I have it show the updating icon as shown here:
![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/3de95d70-df15-4e6e-99fe-2aad6d2d70a7)

I can probably make a toggle that makes this on always for mods that support updates, so you can see which mods support it easier.

**Comment by bladekey88** [comment]
Oh yeah that totally works

**Comment by Mgamerz** [comment]
There is now a menu item in Mod Management that will turn on the view for mod updatability, that lasts for the remainder of the session (it does not persist).
<img width="261" alt="2024-06-04_09h39_51" src="https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/877ba936-5b70-43ee-be19-a076a42251bc">
<img width="294" alt="2024-06-04_09h40_06" src="https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/9bb550ae-9d1b-4254-b792-f0a027914c52">

**Comment by bladekey88** [comment]
That menu item is off by default right?

**Comment by Mgamerz** [comment]
Implemented in 9.0. Yes the option is off by default.
