### ISSUE TITLE
Feature Request - Font Size Accessibility

### ISSUE THREAD

**Issue by ElysiumFic** [ME3Tweaks/MassEffectModManager#405]
I'm old and have old eyes, so I struggle with smaller fonts, which a lot of these tools use because we're dealing with lists with so many items in them a lot of the time.

Thankfully most of the fonts in the tools respond to changing the text size in Windows:
![Text Size](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/18093925/6c39fa74-ad5a-42b9-98e5-cf9a60890eaa)

However, the rest of the interface often doesn't resize to accommodate the larger text, leading to situations like these:
![Starter Kit](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/18093925/ca068800-b9f7-4a22-a6ea-6b4191657e11)
![Button Text](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/18093925/093ab3f2-5aae-4f8e-98c5-25f91e396c0d) (see the button?)
![Package Editor](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/18093925/825ecbf0-fd84-4546-9714-9997eedf07d3)

This is true in both the mod manager and Legendary Explorer, but I'm only going to submit the request here unless advised to do otherwise.

**Comment by Mgamerz** [comment]
I don't think this is very feasible for us to do. A better solution would be to change the scaling in Windows entirely, rather than just the text.
