### ISSUE TITLE
Error installing mod

### ISSUE THREAD

**Issue by Ripthorn** [ME3Tweaks/MassEffectModManager#406]
![Captura de tela 2024-02-26 020741](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/8785487/ec5251a8-02e8-439c-8e9d-7c7d5364d068)
Cannot install the Classic Weapons mod (and maybe others mods too) with the current build.
Thanks god the build from December 31 is still available on Nexus. With this build everything installs with no issues.

**Comment by Mgamerz** [comment]
I have temporarily pulled the latest update until we can figure out what changed in the LegendaryExplorerCore library that changed this behavior. Users will still update to it from older build versions (132 and lower) but 133 users will not update to a newer re-release.

**Comment by stuffi3000** [comment]
@Mgamerz 
![grafik](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/11315157/9b2aba65-10a6-4e0b-a6dc-13fb1fe21864)
I have the same issue when trying to install N7 Warmaster (LE3 version), and I'm already running build 133 of the mod manager... Should I temporarely downgrade to 132?

**Comment by stuffi3000** [comment]
Downgrading to 132 indeed worked.

**Comment by Mgamerz** [comment]
I'm closing this for now as the next update will be Mod Manager 9.
