### ISSUE TITLE
Bug: Mergemods cannot target specific non-INT localized versions of files

### ISSUE THREAD

**Issue by Vakarian89** [ME3Tweaks/MassEffectModManager#407]
I wanted to replace some polish Codex audio files in LE2 and to do this I need to merge into Startup_POL.pcc. The thing is, when I try to serialize moddesc.ini in the editor,  it shows error message that it can't merge into non-startup files at the time. So it seems Startup_POL.pcc isn't a valid target for "filename" property of a merge mod.

**Comment by Mgamerz** [comment]
This will be implemented into Mod Manager 9 - it will strip the localization off the filename in the filename check.

**Comment by Mgamerz** [comment]
Implemented in 9.0
