### ISSUE TITLE
Creating or renaming a batch install overwrites any other batch with the same name

### ISSUE THREAD

**Issue by ghost** [ME3Tweaks/MassEffectModManager#410]
1. Create a batch install for LE2, calling it "My Mods".
![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/83366732/a45fe77f-ff59-4701-b28d-74fa3f8071da)
2. Create or rename a batch install for LE1, also calling it "My Mods".
![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/83366732/fba7d8a4-1af2-4d8a-831f-f64a5de441c9)
The first batch, for a different game, is overwritten.

Expected behavior: Warn or keep both batches.

**Comment by Mgamerz** [comment]
Apparently this was already a known issue in my code that I never got around to implementing

![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/fce56c95-9eba-4fe2-9436-0d888c3021c5)

This is now implemented in the upcoming release of Mod Manager 9.

![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/b9cb2a3a-7be0-44fb-8ce5-b0fc10d06263)

**Comment by Mgamerz** [comment]
Implemented in 9.0
