### ISSUE TITLE
Feature Request: Command Line option to compile merge mod

### ISSUE THREAD

**Issue by DropTheSquid** [ME3Tweaks/MassEffectModManager#417]
M3 is able to do a few things based on a command line params, such as installing a mod or booting a game. It would be really great if we could extend this to handle some of the file drag/drop operations as well, so that they can be used in automating the building of mods. Some things I can do programmatically using LEC code, such as compiling/decompiling TLK and coalesced files. But some functionality is specifically in M3, such as compiling merge mods, so this is one I am particularly interested in. The alternative is to do this part of the mod assembly manually (what I have been doing so far) or directly reference/copy the M3 code, which could lead to out of date/invalid mods. I would rather M3 handled it. 

So, more specifically, I would love to have a new CLI command for M3 that takes in a json file path and attempts to compile an m3m bundle from it, same as if I had dropped that json file onto the program. 

The same could be done for other drag/drop operations, but compiling a merge mod is most important to me. Thanks!

**Comment by Mgamerz** [comment]
Implemented in 9.0
