### ISSUE TITLE
Bug: Error during deployment if LE1 mod with GAME1_EMBEDDED_TLK is packaged together with LE2/LE3/Launcher mods

### ISSUE THREAD

**Issue by Tiran8800** [ME3Tweaks/MassEffectModManager#425]
There is a bug in Mod Manager that prevents you from packing LE1 mods, containing TLK files for GAME1_EMBEDDED_TLK feature, into one archive with mods for other games. This happens only with cmmver 8.0 and higher.

**Comment by Mgamerz** [comment]
This should be fixed now for Mod Manager 9. It was not prefixing the game in multipacks. Thanks for reporting, if you find more bugs please feel free to open an issue.
