### ISSUE TITLE
Feature Request: debug names for LE1 in save selector dialog

### ISSUE THREAD

**Issue by DropTheSquid** [ME3Tweaks/MassEffectModManager#426]
I recently [released a mod](https://www.nexusmods.com/masseffectlegendaryedition/mods/2230) that adds debug saves to LE1. It works perfectly in game, and works ok with mod manager, but Mod Manager does not display the debug names when you select a specific save to boot into. Mod manager can still select a save by number and successfully boot into it. 

It would be really great if this could be updated to support debug names similar to the way it does for 2/3 saves. 
 
There are two ways to set the debug save name. First is embedded within the filename. The filename will be "CharacterId_DebugName_number.pcsav", as opposed to the usual. CharacterId_number.pcsav naming convention. Anything between the underscores is treated as the debug name by my mod. 

You can also set the display name within TSE, and my mod will display that in the list if it differs from the default format. If both are present, the filename takes priority. Debug saves created with the new console command added by the mod use the filename format. 

So, updating the save selector dialog to display the debug name parsed out of the filename and optionally the display name from inside the save file would be very helpful.

**Comment by Mgamerz** [comment]
Looking at values of 'DisplayName' in TSE, those are often random data, so I won't be using those. It blows up the interface as well. I am unsure if our parser is actually correct, it is based on BioWare's code, but we had other problems in it before.

![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/81dd1a68-3c47-43d1-b635-6ceb59323892)

I will only use the filename. Your mod will need to ensure that you cannot use a _ in the name or it will not show anything as I require 2 and only 2 underscores.

![image](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/2738836/3bd8451f-4e96-4e67-9545-19f2b035b385)

**Comment by Mgamerz** [comment]
Implemented in the latest alpha build.

**Comment by DropTheSquid** [comment]
Confirmed this is working. I think it is entirely reasonable to leave out the debug name from inside the save, since it is, as you noted, annoying gibberish by default. The game has some native code that handles that differently if it is non default, but I think it is fine to ignore it here. 

I can update the mod to replace underscores within the name with spaces or something, but we can't technically prevent folks from putting extra underscores in the filename. The mod handles multiple underscores correctly. It would be even better if it handled them, but I am fine letting it gracefully fail if users go around restrictions we have put in place.

**Comment by Mgamerz** [comment]
If users manually edit filenames, I don't think it is reasonable to expect tools to work. Just like when someone changed the casing of the dlc folder names.

**Comment by DropTheSquid** [comment]
Agreed. I think this is more than good enough. I have updated the mod to replace underscores with spaces when they create the save via the mod. I consider this feature done. Thanks for implementing it.

**Comment by Mgamerz** [comment]
Implemented in 9.0
