### ISSUE TITLE
Alternate DLC clone issue

### ISSUE THREAD

**Issue by Leszek90** [ME3Tweaks/MassEffectModManager#451]
When I alter cloned Alternate DLC entry the original one is also altered.

I think that a reference is copied instead of an object clone when I copy an Alternate DLC entry

Version: 9.0 11 July

**Comment by Leszek90** [comment]
![obraz](https://github.com/ME3Tweaks/ME3TweaksModManager/assets/47262300/3175cb7b-3c65-4c77-a589-39a1016b80b4)

**Comment by Mgamerz** [comment]
This should be fixed in the R2 release of July 11 update.
